server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  application:
    name: qqmusic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qqmusic?useSSL=false&serverTimezone=UTC
#    url: jdbc:mysql://123.57.78.66:3306/qqmusic?useSSL=false&serverTimezone=UTC
    username: root
    password: 654321015Gx..
  redis:
    host: 127.0.0.1
    port: 6379
    #password: ???
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

mybatis-plus:
  type-aliases-package: com.qqmusic.entity # 别名扫描包
logging:
  level:
    com.qqmusic: debug
files:
  upload:
    imagespath: /home/hzh/music_server/images/
    musicspath: /home/hzh/music_server/musics/
    lyricspath: /home/hzh/music_server/lyrics/
    coverspath: /home/hzh/music_server/covers/
    imageslocatepath: http://123.57.78.66/images/
    lyricslocatepath: http://123.57.78.66/lyrics/
    musiclocatepath: http://123.57.78.66/musics/
    coverslocatepath: http://123.57.78.66/covers/
#files:
#  upload:
#    imagespath: /Users/gaoxiang/Desktop/images/
#    musicspath: /Users/gaoxiang/Desktop/musics/
#    lyricspath: /Users/gaoxiang/Desktop/lyrics/
#    coverspath: /Users/gaoxiang/Desktop/covers/
